formatVersion: 1
Cloud_Machine: null
inputs:
  hostname1:
    type: string
  user:
    type: string
    title: Username for SSH
    description: The username you would like to have for the installation.
    default: demouser
  password:
    type: string
    pattern: '[a-z0-9A-Z@#$]+'
    encrypted: true
    title: Admin Account Password
    description: The password you would like to use for the System resources
resources:
  Cloud_vSphere_Machine_1:
    type: Cloud.vSphere.Machine
    properties:
      image: VMW-Ubuntu-Cloud
      flavor: VMW-Small
      # customizationSpec: Lin-Cust
      networks:
        - network: '${resource.Cloud_vSphere_Network_1.id}'
          assignment: dynamic
      cloudConfig:
        users:
          - name: '${input.user}'
            sudo:
              - 'ALL=(ALL) NOPASSWD:ALL'
            groups: sudo
            shell: /bin/bash
        runcmd:
          - mkdir -p /root/test
          - 'hostnamectl set-hostname ${input.hostname1}'
          - 'USER=${input.user}'
          - 'PASS=${input.password}'
          - 'echo $USER:$PASS | /usr/sbin/chpasswd'
          - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
          - service ssh reload
          - echo "This output will appear in the log"
        packages:
          - nginx
  Cloud_vSphere_Network_1:
    type: Cloud.vSphere.Network
    properties:
      networkType: existing
      name: VMW-Production
      networkCidr: 172.20.11.0/24
